name: 'Install and cache the dependency'
description: 'Install and cache the dependency'
runs:
  using: 'composite'
  steps:
    - name: cache deps
      id: cache
      uses: actions/cache@v3
      with:
        path: node_modules
        key: deps-node-modules-${{ hashFiles('**/package-lock.json') }}
    - name: Install deps
      if: steps.cache.outputs.cachehit != 'true'
      run: npm ci
      shell: bash